### ISSUE TITLE
Install on Ubuntu 16.04 issues

### ISSUE THREAD

**Issue by tymiles003** [msantl/cryptofolio#10]
I've tried several times to install this app on my virtual server to no avail. Here's the error I received while attempting the python3 manage.py runserver: (ps: I know that I didn't have all the setting placed during this attempt, I still should be able to run the server.)

(cryptofolio) root@enC-Investments:/opt/cryptofolio# python3 manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/cryptofolio/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/cryptofolio/lib/python3.5/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/opt/cryptofolio/lib/python3.5/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/opt/cryptofolio/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/cryptofolio/lib/python3.5/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/cryptofolio/settings.py", line 17, in <module>
    SECRET_KEY = os.environ['SECRET_KEY']
  File "/usr/lib/python3.5/os.py", line 725, in __getitem__
    raise KeyError(key) from None
KeyError: 'SECRET_KEY'

**Comment by msantl** [comment]
Django need the `SECRET_KEY` being set to a value in order work correctly (https://stackoverflow.com/questions/7382149/purpose-of-django-setting-secret-key) 

Without the proper setting of environment variables, like it's stated in the README.md, you won't be able to run the server.

**Comment by tymiles003** [comment]
Sir,
I started the project with django_admin startproject crytofolio, which
added the key. I then created the virtualenv and completed the install with
the little provided information from github. I'm stuck at this point?

**Comment by tymiles003** [comment]
Sir,
I started the project with django_admin startproject crytofolio, which
added the key. I then created the virtualenv and completed the install with
the little provided information from github. I'm stuck at this point?
